### ISSUE TITLE
The assistant takes too long to respond.

### ISSUE THREAD

**Issue by somePythonProgrammer** [somePythonProgrammer/JARVIS#1]
The assistant takes too long to respond, because of improper implementation of wake words. 
We’ll try to implement wake words with porcupine.

**Comment by e-coders** [comment]
but No module named Speech_recongition??

**Comment by e-coders** [comment]
@all-contributors add @somePythonProgrammer for code, ideas, management, documenation

**Comment by e-coders** [comment]
Hmmmm

**Comment by somePythonProgrammer** [comment]
> but No module named Speech_recongition??

Answered in #6

**Comment by e-coders** [comment]
I've fixed - As the SARI is speaking text, It's voice is muted but it's speaking in the Background. see programming-guruji codes of "X=MsgBox("""""")" for info.

**Comment by somePythonProgrammer** [comment]
I've already fixed this, but in an offline project, using pvporcupine.
I am going to upload the remake after some days, so we can call this issue "almost" resolved.
Thanks anyway!

**Comment by somePythonProgrammer** [comment]
Resolved!
